//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_Setup
    {
        public int ID { get; set; }
        public string Serial_no { get; set; }
        public string GMS_No { get; set; }
        public string APN_Name { get; set; }
        public string LAN_IP { get; set; }
        public string LAN_Subnet { get; set; }
        public string LAN_Eski { get; set; }
        public Nullable<byte> NAT { get; set; }
        public Nullable<byte> DHCP_Status { get; set; }
        public string DHCP_Start { get; set; }
        public string DHCP_User { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<byte> Status { get; set; }
        public string UserName { get; set; }
        public string remark { get; set; }
        public byte Flag { get; set; }
        public Nullable<int> Company_ID { get; set; }
    }
}
