//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JetLogin
    {
        public int Jet_ID { get; set; }
        public string JetUsername { get; set; }
        public string JetPassword { get; set; }
        public string JetTitle { get; set; }
    }
}
