//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Log_ID { get; set; }
        public string Ricon_SN { get; set; }
        public string GSM_No { get; set; }
        public string Site_Name { get; set; }
        public Nullable<int> IPSec_Tun1 { get; set; }
        public Nullable<int> IPSec_Tun2 { get; set; }
        public Nullable<int> LAN { get; set; }
        public Nullable<int> Modem0 { get; set; }
        public Nullable<int> Modem1 { get; set; }
        public Nullable<int> LinkBckp { get; set; }
        public Nullable<int> Reboot { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
    }
}
