//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered_Router
    {
        public int Registered_ID { get; set; }
        public string Ricon_SN { get; set; }
        public string GSM_No { get; set; }
        public string Company_Name { get; set; }
        public string Site_Name { get; set; }
    }
}
