//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int Site_ID { get; set; }
        public string Site_Name { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
