//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int User_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string Creator { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_DateTime { get; set; }
        public string LocationStatus { get; set; }
        public int Company_ID { get; set; }
    }
}
