//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZTP_TestEntities : DbContext
    {
        public ZTP_TestEntities()
            : base("name=ZTP_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<GsmNumber> GsmNumber { get; set; }
        public virtual DbSet<Install> Install { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Registered_Router> Registered_Router { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<Basic_Setup> Basic_Setup { get; set; }
        public virtual DbSet<UserLogin45> UserLogin45 { get; set; }
    }
}
